language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - build-tools-24.0.1
    - android-24
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - addon-google_apis-google-24
    
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew
