language: android
android:
  components:
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository
    - extra-google-google_play_services

jdk: oraclejdk7

before_install:
  - chmod +x gradlew
